### PR TITLE
Allowing to specify patterns for ignored repos during org linking

### LINKED ISSUE #157: Option to exclude repositories if organization is linked
When you link an organization, a github orga webhook is installed which adds the PR check for every PR of every repository. It is desirable though, to be able to exclude repositories from this, so all repositories from orga n _excluding_ repos x, y & z are linked. In certain scenarios it is much less effort to link an orga and exclude some repositories than selectively including only the desired repositories (and take care that future repositories get added too).

One idea (UI-wise) might be the option to supply a repo pattern for a linked orga which is used to match repository names against.

### PR DESCRIPTION
**Pull request by dennisoelkers**
This change adds a field "excludePattern" to the org model, which allows to specify a comma-separated list of repository names or substrings which are matched against the repository of an incoming or rechecked PR. If the string matches against the repo name, the PR is ignored and no
CLA check is done.

Fixes #157.

### CODE REVIEW

**Comment by KharitonOff** [comment]
Great job! 👍  Thank you for your contribution! 😄  It works good so far.
We appreciate it very much.

The only point I have: there is no way to find out which repos/pattern I've excluded after the org is linked. I could imagine to have this info as a popover placed on the org name or even better as a modal view, where the user can edit this entry.

**Comment by dennisoelkers** [comment]
Thanks for your quick review and feedback, I appreciate it very much! I am right now to add some test coverage for the `isRepoExcluded` function, so coveralls is happy again. After that I will add a popover to the organization list, that's a good idea!

I actually had in mind to add a function to the organization action menu which allows you to edit the pattern string, but that's a bit more work than the part which allows you to specify one during linking.

**Comment by dennisoelkers** [comment]
Is there a chance to get this merged and deployed to cla-assistant.io? We would have to set up our own instance otherwise.

**Comment by KharitonOff** [comment]
Sure. This week or next week I'm going to take some time for review. After that we can take over your changes into CLA assistant

**Comment by KharitonOff** [comment]
Great job! Thank you for your contribution 👍 
It looks good for me. 
I did some minor changes on the UI: place the tooltip only on the org name and adjusted it's text for the orgs without exclude pattern. I hope you are ok with it.

**Comment by fr34kyn01535** [comment]
I would love to be able to edit the pattern once i linked a organization

**Comment by KharitonOff** [comment]
@fr34kyn01535 this feature is not implemented yet, but you are very welcome to make a contribution to this project 😏  See issue #182

**Pull request merged**
