### PR TITLE
Spelling

### PR DESCRIPTION
**Pull request by jsoref**
Generated by https://github.com/jsoref/spelling `f`; to maintain your repo, please consider `fchurn`

### CODE REVIEW

**Comment by KharitonOff** [comment]
Thank you very much for your findings 👍

**Comment by jsoref** [comment]
> this is the only commit I am not willing to accept because of function name changes. The risk of potential side effects and amount of work for testing are to high in relation to the benefit of the new name.

Even before rebasing/folding, GitHub wouldn't explain which changes this comment was about.

I've left comments for the things that _might_ match your review, if you indicate which it was for, I'll drop them.

**Comment by KharitonOff** [comment]
Oh I'm sorry for that, I didn't realise that it is not clear in github which commit I meant, but you spotted it correctly (fb50b4e74887a9e5d942aaddf821f84f289b4efb)
Probably you are right with your assumption that there are only local names changed. But I still don't like the idea to change function names. I don't see any reason for doing it. Let's say we would change the function name `callGithub` to `callGitHub`, then we should also change the variable name `github` to `gitHub` in order to remain conform with the new "naming convention"... and this would definitely cause unexpected side effects since the `githubService` is used everywhere in the app.
So my proposal would be to skip this commit and takeover all other changes.

**Comment by jsoref** [comment]
I've stripped github to text changes d25c923. And to address a comment I made initially, I've added 7ac40a6.

**Comment by KharitonOff** [comment]
Thanks again!

**Pull request merged**
