### PR TITLE
implemented my signed CLAs feature

### LINKED ISSUE #606: Annulment of signed CLAs
We are considering  developing  and adding a dashboard for users that have signed a CLA through the cla-assitant, through which they can view their signed CLAs and cancel them.

The workflow would consist of:

(1) User goes to CLA-ASSITANT and click on my signed CLAs
(2) User sees a list of repos/orgs and which CLAs he/she had signed with them
(3) User clicks on a specific signed CLA and selects ANNUL  (with confirmation)
(4) We remove the information that the user has an active signed CLA with the selected repo/org
(5) We keep some information that the user had previously signed the CLA from date - to date

Would you consider incorporating this feature back into the upstream project?

Reasoning: due to GDPR we are required to remove saved information from the database (after X years) upon cancellation of the CLA. Once a user retracts his/her agreement to a CLA, any future contributions will require re-signing of the CLA. This is currently not an option in the cla-assitant.

<sub> Basem Vaseghi <basem.vaseghi@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

### PR DESCRIPTION
**Pull request by rael312**
fixes #606 
 
*  added my-cla button and view
 *  added revoke CLA functionality
 *  contributor report window shows latest entry per user
 *  export has complete history
 *  Navbar home navigation fixed
 *  getGist changed to free API
 * cla/getAll now returns all CLAs filtering for distinct clas moved to respective uses of API
 *  fixed acceptance tests
 *  added environment variables for acceptance tests (TEST_HOST, TEST_CLA_USER)
 *  added more waits to acceptances tests to reduce errors caused by timeouts
 

 <sub> Clemens Krämer <clemens.kraemer@daimler.com>, Daimler TSS GmbH, [legal info/Impressum](https://github.com/Daimler/daimler-foss/blob/master/LEGAL_IMPRINT.md)</sub>

### CODE REVIEW

**Comment by michael-spengler** [comment]
@rael312 Thank You very much for your contribution. We'll review and potentially merge your PR during this week.

**Comment by michael-spengler** [comment]
@rael312 We conducted some first tests before considering the merge of your PR. At least with our local setup the features you added do not work out of the box. For example when it comes to clicking the button "View my signed CLAs" which you introduced, we can's see any results. If we then add the .../my-cla route manually we get the following error:

cla-error-1

Solution Proposal: Would it be fine for you have a google meet or MS Teams Meeting with us on solving this issue?

@oganexon, @ibakshay  or I would be available to join and we are relatively flexible from a time perspective. 
If you use telegram, you could also join us in [here](https://t.me/joinchat/ubxm6GEcPaRiNjAy). 

We would be happy to work with you to get those features into our repo...

**Comment by clat2** [comment]
@michael-spengler Hi, your error suggests to me that you are not running the code of the pull requests. The error you are showing is caused by a call that has been replaced by me in src/client/controller/my-cla.js line 22. 

If you are still running into issues, we can schedule a meeting to solve them.

**Comment by rael312** [comment]
@michael-spengler Hi, your error suggests to me that you are not running the code of the pull requests. The error you are showing is caused by a call that has been replaced by me in src/client/controller/my-cla.js line 22. 

If you are still running into issues, we can schedule a meeting to solve them.

**Review by oganexon — CHANGES_REQUESTED** [review]
Hi @rael312
Thanks for contributing, we apologize that it's taking so long.
After further testing, we no longer have the problem described above, we probably handled it wrong.

Before merging the branch, could you make sure that the DeepScan checks are successful?
Once this is done, I think everything will be good.

**Comment by michael-spengler** [comment]
Merging this PR however not creating a corresponding release as we want to check how to deal with revoking signatures (GDPR...) holistically also in the context of the new [CLA Assistant](https://github.com/cla-assistant/github-action) (GitHub Action based CLA Handling).

--> The instance which we are running will not (yet?) be updated accordingly.

**Pull request merged**
