### PR TITLE
Sign only once when multiple orgs or repos lined with the same gist

### PR DESCRIPTION
**Pull request by MichaelTsengLZ**
One scenario I still not sure and want to discuss. When a admin want to try the new feature and re-link a repo with the same gist but mark it as a shared gist with other repos. Do we need contributors who have already signed the repo gist to sign again? 

UI:
screen shot 2017-07-20 at 1 15 59 am
screen shot 2017-07-20 at 10 37 44 pm

### CODE REVIEW

**Comment by jeffmcaffer** [comment]
Switching the sharing flag is like changing the gist.  The contract is different so people should be made aware and resign.  It might be good to warn admins when they change the flag.

**Comment by KharitonOff** [comment]
Hm, I think there is no difference for the enduser, since he/she has signed the same CLA. So whether the flag is on or off, I as a signer accept the content of the CLA regardless of the number of repos/orgs this CLA is linked to. But it's just my opinion :)

**Comment by thojansen** [comment]
Question: Suppose Repos A, B and C use CLA1, all have activated this on a per-repo basis and a given user has signed A/ CLA1. Then after an admin switches to a per-CLA basis, I would assume that he would still need to sign let say a PR for B once to actually sign it on a per-CLA basis. After that, a PR for C would be already signed.

This would be the same logic as we had when switching from a repo to org level. We store what is signed on which level to do the actual checks.

**Comment by MichaelTsengLZ** [comment]
Yes, this PR can satisfy your case. The contributor needs to re-sign CLA1 only once on a per-CLA basis for B or C. But my follow up question is: does the contributor who already signed A/ CLA1 on a per-repo basis still need to sign A/ CLA1 on a per-CLA basis? @thojansen

**Comment by thojansen** [comment]
No, I would think that this is still valid.

**Comment by MichaelTsengLZ** [comment]
OK. I made some changes to support that scenario. Could you take a look, please?

**Comment by MichaelTsengLZ** [comment]
And add a column here as shown in the image.
screen shot 2017-07-24 at 3 06 17 pm

**Comment by KharitonOff** [comment]
@MichaelTsengLZ thank you for your PR! We appreciate it very much! 
Unfortunately I have not enough time to review and test it now :( Currently I'm stuck in an other project and will go on vacation soon... It could take up to a month until I'll be able to review it. Sorry for that.

**Comment by MichaelTsengLZ** [comment]
@KharitonOff OK. Because we are trying to make some changes to solve other issues(#251, #252 etc.) during the month. We will send out another PR to give you a sense of where we are heading to.

**Comment by KharitonOff** [comment]
I think we need just one more thing... 
This checkbox could be confusing for many users. There should be an explanation about what exactly happens if I "share the gist". We can add a description like it is done for "Select from Gist   (don't have one?)"

**Comment by MichaelTsengLZ** [comment]
@KharitonOff Sure. I will add it today or tomorrow. Thank you so much for reviewing this. After this one merged, I will send one more PR that I've been working on.

**Comment by MichaelTsengLZ** [comment]
Any suggestions on the wording?

**Pull request merged**
