### PR TITLE
Multiple changes to enable bigger repo scale

### PR DESCRIPTION
**Pull request by MichaelTsengLZ**
Hello SAP team, thank you so much for your awesome project. Microsoft Open Source Program Office team has adopted and modified it to protect all Microsoft repos successfully. Now I have a list of features that want to contribute back to help the CLA-Assistant works properly for larger scale.
We are happy to break this big PR into multiple PRs based on features.

Feature list:
1. Overridden CLA and Null CLA for linked orgs
Because there are some repos in an org that don’t share the same CLA with their org. An override CLA for those repos is necessary.
What’s more, some repos in an org may not need CLA at all. So a null type CLA is introduced. It's better than the exempt list because it can be managed like other CLA, which means we can delete a null CLA repo without relinking the org.

2. Enable terminate signed CLA
To mark a previous CLA signature as terminated.

3. Skip CLA for a small contribution.
In order to minimize the friction to make a contribution, CLA is not required when a pull request is relatively small as defined by UI settings.

4. Expose add/terminate/check a CLA and link/unlink a repo/org API
The CLA-Assistant is just one part of the open source management system. Expose APIs for other micro services.

5. Add submitter mode
Only require the PR submitter to sign a CLA instead of all the committers. It can be changed in the configuration settings.

6. Reduce GitHub call
I have some changes that reduce token usage by around 40%

7. Minor UI changes
8. Some bugfixes

### CODE REVIEW

**Comment by KharitonOff** [comment]
Amazing! Thank you so much for such a huge contribution!
I think it will take some time to review and test your PR 😄 

btw. I'm currently working on similar topics like point 6 and 7... I also added some calls to GitHub's GraphQL-APIs. I hope we'll get not so many merge conflicts 😏

**Comment by MichaelTsengLZ** [comment]
We are happy to contribute to these awesome project. :)

**Comment by thojansen** [comment]
Really impressive work !!!

Would Microsoft be interested in a discussion on the future setup/ direction of CLA assistant? Given the amount of contributions so far that would be more than reasonable. Maybe there are some opportunities.

**Comment by MichaelTsengLZ** [comment]
Hi friends. I found some bugs on the master branch.
1. When a pull request is not from a repo that has been stored in user requests before, it will throw an error. I fix it in this [commit](https://github.com/cla-assistant/cla-assistant/pull/275/commits/601e02fb4d853df3423aa8ea1cac2363210292fd).
2. GraphQL returns databaseId as the user id. I fix it [here](https://github.com/cla-assistant/cla-assistant/pull/275/commits/4ae6b7a967fdfbea2cfd7723b450a56315b12cac)
3. Getting Github paging data has problems. I fix it [here](https://github.com/cla-assistant/cla-assistant/pull/275/commits/844a43fc6fcf389592eda8823aee7b748996917c).

**Comment by MichaelTsengLZ** [comment]
Yeah. Thank you so much 👍 👍 👍

**Pull request merged**
