### PR TITLE
Enable textarea and hidden fields support

### PR DESCRIPTION
**Pull request by mickaelandrieu**
Hello @thojansen,

I  think this is the only required update to fix https://github.com/cla-assistant/cla-assistant/issues/143.

Also, I need to display a textarea (this is why I've found your issue), for instance to ask for a postal address.

What do you think?

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/cla-assistant/cla-assistant/pull/204" target="_blank">ReviewNinja

**Comment by KharitonOff** [comment]
👍  thank you for your PR. Can you test the changes in https://preview.cla-assistant.io please?

**Comment by mickaelandrieu** [comment]
@KharitonOff  Yes I will give a try today, thanks for the merge. I have 1 question regarding the way the data are stored on your service: can you confirm this is not stored on SAP servers (for the mongodb part)? This is a very important information for me (should we use the service or should we host it ?).

**Comment by KharitonOff** [comment]
@mickaelandrieu Yes, I can confirm that the data is not stored on SAP servers (yet), we use mlab.com as mongodb service provider. However I can't say how long we'll keep the status quo, med- or longterm we would like to move to our own infrastructure (based on CloudFoundry), but there are no concrete plans so far.

**Comment by mickaelandrieu** [comment]
@KharitonOff textarea feature works as expected (for my needs)

textare_ok

As I don't understand who can be interested by a hidden field, I don't know how to test it: is it only to pass data? And if yes, why?

Regarding the data storage, will we be notified if the data are moved to SAP servers "before"? It's very important for us to ensure our contributors that their data are not offered to any company, at least, not used by any company.

**Comment by thojansen** [comment]
@mickaelandrieu we had a discussion regarding this #141 and have changed our ToS as a reaction of that issue.
https://gist.github.com/CLAassistant/3a73e4cd729c9d0a6e30/revisions

This should clarify how the data stored can be used. 
> ..for purposes of operating and improving the Website and Tool

SAP has no interest in using that data for any other purposes and the physical location of the data storage will not change that. Legally the offered service is bound to the ToS.

**Comment by mickaelandrieu** [comment]
Thnks for the additional information @thojansen, it's fair :)

**Pull request merged**
