### PR TITLE
Add dockerfile

### PR DESCRIPTION
**Pull request by ketan**
I could not find a docker image on dockerhub or a `Dockerfile` to be able to build one. So I've created this for my own use. Would be nice to have this part of the core.

Would you be able to publish (stable) images on dockerhub as well — it's mostly straight forward to do that.

### CODE REVIEW

**Comment by ketan** [comment]
Ping?

**Comment by ketan** [comment]
Any thoughts?

**Comment by KharitonOff** [comment]
Great idea! I just would like to test it first before merging. Unfortunately I don't have much time currently, so excuse the longer delay, please. As long it's not a mission critical feature I allow me to postpone it ;)
I keep in mind your PR!

**Comment by ketan** [comment]
If it counts, we've been running this on https://cla.gocd.io for a few weeks now.

**Comment by KharitonOff** [comment]
ok :)

**Pull request merged**
