### PR TITLE
Simplify apk package clean up in Dockerfile with virtual package, again

### PR DESCRIPTION
**Pull request by PeterDaveHello**
Originally made in #639 with a mistake and fixed/reverted by @ibakshay in 98705b636c65fb771b0d68c80a5a262d1fca3fc8, the problem should be fixed now!

### CODE REVIEW

**Comment by PeterDaveHello** [comment]
Hi @KharitonOff, do you have a minute to help review this PR? Thanks!

**Comment by PeterDaveHello** [comment]
Not sure if @michael-spengler or @ibakshay can help take a look? Thanks.

**Comment by michael-spengler** [comment]
@PeterDaveHello: Finally we'll look into this. Update follows in the upcoming week. Feel free to join our little [telegram group](https://t.me/joinchat/ubxm6GEcPaRiNjAy ), so we might also have a short online meeting together.

**Review by michael-spengler — APPROVED** [review]
Tested on Maëls Machine...

**Pull request merged**
